[package]
name = "rust-lapper"
version = "0.4.4"
authors = ["Seth Stadick <sstadick@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/sstadick/rust-lapper"
description = "A fast and easy interval overlap library"
documentation = "https://docs.rs/rust-lapper"
readme = "README.md"
categories = ["algorithms", "science"]
keywords = ["tree", "interval", "bioinformatics", "ranges", "genomic"]

[lib]
name = "rust_lapper"
path = "src/lib.rs"

[[bin]]
name = "bed_cov"
path = "src/main.rs"

[dependencies]
clap = "2.33.1"

[dev-dependencies]
criterion = "0.3"
rand = "0.7"
cpu-time = "0.1.0"

[[bench]]
name = "lapper_benchmark"
harness = false
